package com.credai.dynamoDb.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import lombok.Data;

@DynamoDBTable(tableName = "Customer")
@Data
public class Customer {
	
	@DynamoDBHashKey(attributeName = "custId") 
    @DynamoDBAutoGeneratedKey              
    private String custId;

    @DynamoDBAttribute(attributeName = "firstName")
    @NotBlank(message="FirstName cannot be blank")
    private String firstName;

    @DynamoDBAttribute(attributeName = "lastName")
    @NotBlank(message="LastName cannot be blank")
    private String lastName;

    @DynamoDBAttribute(attributeName = "dob")
    @NotBlank(message="DOB cannot be blank")
    private String dob;
    
    @DynamoDBAttribute(attributeName = "phone")
    @NotBlank(message = "Phone number cannot be blank")
    @Pattern(regexp = "\\d{10}", message = "Phone number must be 10 digits")
    private String phone;
    
    @DynamoDBAttribute(attributeName = "email")
    @NotBlank(message = "Email cannot be blank")
    @Pattern(regexp = "^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$", message = "Invalid email format")
    private String email;

}
